global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ms-pedidos'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/actuator/prometheus'
  - job_name: 'ms-productos-v2'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/actuator/prometheus'
  - job_name: 'gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'
  - job_name: 'ms-config-server'
    static_configs:
      - targets: ['host.docker.internal:8888']
    metrics_path: '/actuator/prometheus'
  - job_name: 'registry-service'
    static_configs:
      - targets: ['host.docker.internal:8761']
    metrics_path: '/actuator/prometheus'
