spring:
  application:
    name: oauth-server
server:
  port: 9000
logging:
  level:
    org.springframework.security: ERROR
eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/
